.prepare-app-build:
  stage: prepare
  extends:
    - .artifacts-always-one-day
    - .image-aarch64
    - .gitlab-runner-tag
  script:
    - make deps

.build-aarch64-app:
  stage: build
  extends:
    - .artifacts-always-one-week
    - .image-aarch64
    - .gitlab-runner-tag
  before_script:
    - make deps-extract
  script:
    - make all
